context("Collapsing cycles")
test_that("collapsing the cycles", {
  collapse_test <- standards %>%
    isoreader::iso_get_raw_data() %>%
    find_bad_cycles() %>%
    spread_match() %>%
    append_ref_deltas(standards) %>%
    delta_values(genplot=FALSE) %>%
    collapse_cycles()
  expect_is(collapse_test, "tbl_df")
  expect_true("d45_mean" %in% colnames(collapse_test))
  expect_true("d46_mean" %in% colnames(collapse_test))
  expect_true("d47_mean" %in% colnames(collapse_test))
  expect_true("d48_mean" %in% colnames(collapse_test))
  expect_true("d49_mean" %in% colnames(collapse_test))
  expect_true("d18O_PDBCO2_mean" %in% colnames(collapse_test))
  expect_true("d18O_PDB_mean" %in% colnames(collapse_test))
  expect_true("d13C_PDB_mean" %in% colnames(collapse_test))
  expect_true("D47_raw_mean" %in% colnames(collapse_test))
  expect_true("D48_raw_mean" %in% colnames(collapse_test))
  expect_true("D49_raw_mean" %in% colnames(collapse_test))
  expect_true("param_49_mean" %in% colnames(collapse_test))
  expect_true("d45_sd" %in% colnames(collapse_test))
  expect_true("d46_sd" %in% colnames(collapse_test))
  expect_true("d47_sd" %in% colnames(collapse_test))
  expect_true("d48_sd" %in% colnames(collapse_test))
  expect_true("d49_sd" %in% colnames(collapse_test))
  expect_true("d18O_PDBCO2_sd" %in% colnames(collapse_test))
  expect_true("d18O_PDB_sd" %in% colnames(collapse_test))
  expect_true("d13C_PDB_sd" %in% colnames(collapse_test))
  expect_true("D47_raw_sd" %in% colnames(collapse_test))
  expect_true("D48_raw_sd" %in% colnames(collapse_test))
  expect_true("D49_raw_sd" %in% colnames(collapse_test))
  expect_true("param_49_sd" %in% colnames(collapse_test))
  expect_true("d45_n" %in% colnames(collapse_test))
  expect_true("d46_n" %in% colnames(collapse_test))
  expect_true("d47_n" %in% colnames(collapse_test))
  expect_true("d48_n" %in% colnames(collapse_test))
  expect_true("d49_n" %in% colnames(collapse_test))
  expect_true("d18O_PDBCO2_n" %in% colnames(collapse_test))
  expect_true("d18O_PDB_n" %in% colnames(collapse_test))
  expect_true("d13C_PDB_n" %in% colnames(collapse_test))
  expect_true("D47_raw_n" %in% colnames(collapse_test))
  expect_true("D48_raw_n" %in% colnames(collapse_test))
  expect_true("D49_raw_n" %in% colnames(collapse_test))
  expect_true("param_49_n" %in% colnames(collapse_test))
  expect_true("d45_sem" %in% colnames(collapse_test))
  expect_true("d46_sem" %in% colnames(collapse_test))
  expect_true("d47_sem" %in% colnames(collapse_test))
  expect_true("d48_sem" %in% colnames(collapse_test))
  expect_true("d49_sem" %in% colnames(collapse_test))
  expect_true("d18O_PDBCO2_sem" %in% colnames(collapse_test))
  expect_true("d18O_PDB_sem" %in% colnames(collapse_test))
  expect_true("d13C_PDB_sem" %in% colnames(collapse_test))
  expect_true("D47_raw_sem" %in% colnames(collapse_test))
  expect_true("D48_raw_sem" %in% colnames(collapse_test))
  expect_true("D49_raw_sem" %in% colnames(collapse_test))
  expect_true("param_49_sem" %in% colnames(collapse_test))
})
